"use client";

import { useActionState, useId } from "react";
import { useFormStatus } from "react-dom";
import { activateRental } from "@/app/(dashboard)/rentals/actions";
import { initialRentalActionState } from "@/lib/rentals/action-state";
import type { ActivatableBooking, RentalWorkspaceData } from "@/lib/services/rentals";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { StatusBadge } from "@/components/feedback/status-badge";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"});
const date=(value:string)=>value?new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"Not scheduled";
export function RentalWorkspace({data}:{data:RentalWorkspaceData}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.totals).map(([key,value])=><Card key={key}><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs capitalize text-muted-foreground">{key.replace(/([A-Z])/g," $1")}</p></CardContent></Card>)}</div>{data.canActivate?<Card><CardHeader><CardTitle>Ready to start</CardTitle><CardDescription>Only confirmed bookings can become active contracts. Activation is atomic and cannot be repeated.</CardDescription></CardHeader><CardContent className="grid gap-3 xl:grid-cols-2">{data.confirmedBookings.map(booking=><ActivationForm key={booking.id} booking={booking}/>)}{data.confirmedBookings.length===0?<p className="py-8 text-center text-sm text-muted-foreground xl:col-span-2">No confirmed bookings are waiting for activation.</p>:null}</CardContent></Card>:null}<Card><CardHeader><CardTitle>Rental control board</CardTitle><CardDescription>Live contracts derived from booking and fleet state.</CardDescription></CardHeader><CardContent className="space-y-3">{data.rentals.map(rental=><article key={rental.id} className="flex flex-col justify-between gap-3 rounded-xl border border-border/80 p-4 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{rental.number}</p><StatusBadge status={rental.status}/></div><p className="mt-1 text-sm">{rental.customer} · {rental.vehicle}</p><p className="mt-1 text-xs text-muted-foreground">Started {date(rental.startedAt)} · Due {date(rental.plannedEndAt)} · Start odo {rental.startOdometer.toLocaleString("en-IN")} km</p></div><p className="font-semibold">{money.format(rental.total)}</p></article>)}{data.rentals.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No rental contracts yet.</p>:null}</CardContent></Card></div>}
function ActivationForm({booking}:{booking:ActivatableBooking}){const[state,action]=useActionState(activateRental,initialRentalActionState);const dateId=useId(),odoId=useId();const min=new Date(booking.startsAt).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16),max=new Date(booking.endsAt).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16);return <form action={action} className="space-y-3 rounded-xl border border-border/80 bg-muted/10 p-4"><input type="hidden" name="bookingId" value={booking.id}/><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{booking.number} · {booking.customer}</p><p className="text-xs text-muted-foreground">{booking.vehicle} · {money.format(booking.total)}</p></div><StatusBadge status="confirmed"/></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor={dateId}>Actual start</Label><Input id={dateId} name="startedAt" type="datetime-local" min={min} max={max} defaultValue={min} required/></div><div><Label htmlFor={odoId}>Start odometer (km)</Label><Input id={odoId} name="startOdometer" type="number" min={booking.currentOdometer} defaultValue={booking.currentOdometer} required/></div></div><Submit/><p className={state.status==="error"?"text-xs text-destructive":"text-xs text-emerald-500"} role="status">{state.message}</p></form>}
function Submit(){const{pending}=useFormStatus();return <Button type="submit" disabled={pending}>{pending?"Activating…":"Start rental"}</Button>}
