"use client";

import { useActionState, useId, useState } from "react";
import { useFormStatus } from "react-dom";
import { activateRental, extendActiveRental, swapVehicle } from "@/app/(dashboard)/rentals/actions";
import { initialRentalActionState } from "@/lib/rentals/action-state";
import type { ActivatableBooking, RentalRecord, RentalWorkspaceData, ReplacementVehicle } from "@/lib/services/rentals";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { StatusBadge } from "@/components/feedback/status-badge";

const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"});
const date=(value:string)=>value?new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"Not scheduled";
export function RentalWorkspace({data}:{data:RentalWorkspaceData}){return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.totals).map(([key,value])=><Card key={key}><CardContent className="p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs capitalize text-muted-foreground">{key.replace(/([A-Z])/g," $1")}</p></CardContent></Card>)}</div>{data.canActivate?<Card><CardHeader><CardTitle>Ready to start</CardTitle><CardDescription>Only confirmed bookings can become active contracts. Activation is atomic and cannot be repeated.</CardDescription></CardHeader><CardContent className="grid gap-3 xl:grid-cols-2">{data.confirmedBookings.map(booking=><ActivationForm key={booking.id} booking={booking}/>)}{data.confirmedBookings.length===0?<p className="py-8 text-center text-sm text-muted-foreground xl:col-span-2">No confirmed bookings are waiting for activation.</p>:null}</CardContent></Card>:null}<Card><CardHeader><CardTitle>Rental control board</CardTitle><CardDescription>Live contracts with separately tracked extension charges and vehicle assignment history.</CardDescription></CardHeader><CardContent className="space-y-3">{data.rentals.map(rental=><article key={rental.id} className="grid gap-4 rounded-xl border border-border/80 p-4 xl:grid-cols-[1fr_auto] xl:items-start"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{rental.number}</p><StatusBadge status={rental.status}/></div><p className="mt-1 text-sm">{rental.customer} · {rental.vehicle}</p><p className="mt-1 text-xs text-muted-foreground">Started {date(rental.startedAt)} · Due {date(rental.plannedEndAt)} · Start odo {rental.startOdometer.toLocaleString("en-IN")} km</p><p className="mt-2 text-xs text-muted-foreground">Contract {money.format(rental.contractAmount)}{rental.extensionAmount>0?` · Extensions ${money.format(rental.extensionAmount)}`:""}</p></div><div className="space-y-3 xl:min-w-80"><p className="text-right font-semibold">{money.format(rental.total)}</p>{data.canExtend&&rental.plannedEndAt&&(rental.status==="active"||rental.status==="overdue")?<ExtensionForm rental={rental}/>:null}{data.canSwap&&rental.status==="active"&&rental.plannedEndAt&&new Date(rental.plannedEndAt)>new Date()&&data.replacementVehicles.length>0?<SwapForm rental={rental} vehicles={data.replacementVehicles}/>:null}</div></article>)}{data.rentals.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No rental contracts yet.</p>:null}</CardContent></Card></div>}
function ActivationForm({booking}:{booking:ActivatableBooking}){const[state,action]=useActionState(activateRental,initialRentalActionState);const dateId=useId(),odoId=useId();const min=new Date(booking.startsAt).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16),max=new Date(booking.endsAt).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16);return <form action={action} className="space-y-3 rounded-xl border border-border/80 bg-muted/10 p-4"><input type="hidden" name="bookingId" value={booking.id}/><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{booking.number} · {booking.customer}</p><p className="text-xs text-muted-foreground">{booking.vehicle} · {money.format(booking.total)}</p></div><StatusBadge status="confirmed"/></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor={dateId}>Actual start</Label><Input id={dateId} name="startedAt" type="datetime-local" min={min} max={max} defaultValue={min} required/></div><div><Label htmlFor={odoId}>Start odometer (km)</Label><Input id={odoId} name="startOdometer" type="number" min={booking.currentOdometer} defaultValue={booking.currentOdometer} required/></div></div><Submit/><p className={state.status==="error"?"text-xs text-destructive":"text-xs text-emerald-500"} role="status">{state.message}</p></form>}
function Submit(){const{pending}=useFormStatus();return <Button type="submit" disabled={pending}>{pending?"Activating…":"Start rental"}</Button>}

function ExtensionForm({rental}:{rental:RentalRecord}){const[state,action]=useActionState(extendActiveRental,initialRentalActionState);const endId=useId(),reasonId=useId();const current=new Date(rental.plannedEndAt);const minDate=new Date(current.getTime()+60000).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16);const suggested=new Date(current.getTime()+86400000).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16);return <form action={action} className="space-y-2 rounded-lg border border-border/70 bg-muted/10 p-3"><input type="hidden" name="rentalId" value={rental.id}/><div className="grid gap-2 sm:grid-cols-2"><div><Label htmlFor={endId}>Extend until</Label><Input id={endId} name="extendedEndAt" type="datetime-local" min={minDate} defaultValue={suggested} required/></div><div><Label htmlFor={reasonId}>Reason</Label><Input id={reasonId} name="reason" minLength={3} maxLength={500} placeholder="Customer request"/></div></div><ExtensionSubmit/><p className={state.status==="error"?"text-xs text-destructive":"text-xs text-emerald-500"} role="status">{state.message}</p></form>}
function ExtensionSubmit(){const{pending}=useFormStatus();return <Button type="submit" size="sm" variant="outline" disabled={pending}>{pending?"Extending…":"Extend rental"}</Button>}

function SwapForm({rental,vehicles}:{rental:RentalRecord;vehicles:ReplacementVehicle[]}){const[state,action]=useActionState(swapVehicle,initialRentalActionState);const options=vehicles.filter(vehicle=>vehicle.id!==rental.bikeId);const[selectedId,setSelectedId]=useState(options[0]?.id??"");const selected=options.find(vehicle=>vehicle.id===selectedId);const vehicleId=useId(),timeId=useId(),oldOdoId=useId(),newOdoId=useId(),statusId=useId(),reasonId=useId();const now=new Date().toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16),max=new Date(rental.plannedEndAt).toLocaleString("sv-SE",{timeZone:"Asia/Kolkata"}).slice(0,16);if(!options.length)return null;return <form action={action} className="space-y-2 rounded-lg border border-border/70 bg-muted/10 p-3"><input type="hidden" name="rentalId" value={rental.id}/><div className="grid gap-2 sm:grid-cols-2"><div><Label htmlFor={vehicleId}>Replacement vehicle</Label><select id={vehicleId} name="toBikeId" value={selectedId} onChange={event=>setSelectedId(event.target.value)} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" required>{options.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.label} · {vehicle.batteryLevel}%</option>)}</select></div><div><Label htmlFor={timeId}>Swap time</Label><Input id={timeId} name="swappedAt" type="datetime-local" defaultValue={now} max={max} required/></div><div><Label htmlFor={oldOdoId}>Returned odometer</Label><Input id={oldOdoId} name="fromReturnOdometer" type="number" min={rental.currentOdometer} defaultValue={rental.currentOdometer} required/></div><div><Label htmlFor={newOdoId}>Replacement odometer</Label><Input key={selectedId} id={newOdoId} name="toStartOdometer" type="number" min={selected?.currentOdometer??0} defaultValue={selected?.currentOdometer??0} required/></div><div><Label htmlFor={statusId}>Returned vehicle</Label><select id={statusId} name="returnedVehicleStatus" defaultValue="maintenance" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="maintenance">Send to maintenance</option><option value="available">Keep available</option></select></div><div><Label htmlFor={reasonId}>Reason</Label><Input id={reasonId} name="reason" minLength={3} maxLength={500} placeholder="Breakdown or customer request" required/></div></div><SwapSubmit/><p className={state.status==="error"?"text-xs text-destructive":"text-xs text-emerald-500"} role="status">{state.message}</p></form>}
function SwapSubmit(){const{pending}=useFormStatus();return <Button type="submit" size="sm" variant="outline" disabled={pending}>{pending?"Swapping…":"Swap vehicle"}</Button>}
