"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { activateBooking, extendRental, recordRentalReturn, settleReturnedRental, swapRentalVehicle } from "@/lib/services/rentals";
import type { RentalActionState } from "@/lib/rentals/action-state";

const schema=z.object({bookingId:z.string().uuid(),startedAt:z.iso.datetime({local:true}),startOdometer:z.coerce.number().int().min(0).max(10000000)});
export async function activateRental(_:RentalActionState,formData:FormData):Promise<RentalActionState>{const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check activation details"};try{const result=await activateBooking({...parsed.data,startedAt:new Date(`${parsed.data.startedAt}:00+05:30`).toISOString()});revalidatePath("/rentals");revalidatePath("/bookings");revalidatePath("/fleet");revalidatePath("/");return{status:"success",message:`${result.rentalNumber} activated`};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Unable to activate rental"};}}

const extensionSchema=z.object({rentalId:z.string().uuid(),extendedEndAt:z.iso.datetime({local:true}),reason:z.string().trim().max(500).optional()});
export async function extendActiveRental(_:RentalActionState,formData:FormData):Promise<RentalActionState>{const parsed=extensionSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check extension details"};try{const result=await extendRental({...parsed.data,extendedEndAt:new Date(`${parsed.data.extendedEndAt}:00+05:30`).toISOString()});revalidatePath("/rentals");revalidatePath("/bookings");revalidatePath("/fleet");revalidatePath("/");return{status:"success",message:`${result.rentalNumber} extended · ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(result.extensionAmount)} added`};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Unable to extend rental"};}}

const swapSchema=z.object({rentalId:z.string().uuid(),toBikeId:z.string().uuid(),swappedAt:z.iso.datetime({local:true}),fromReturnOdometer:z.coerce.number().int().min(0).max(10000000),toStartOdometer:z.coerce.number().int().min(0).max(10000000),returnedVehicleStatus:z.enum(["available","maintenance"]),reason:z.string().trim().min(3).max(500)});
export async function swapVehicle(_:RentalActionState,formData:FormData):Promise<RentalActionState>{const parsed=swapSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check swap details"};try{const result=await swapRentalVehicle({...parsed.data,swappedAt:new Date(`${parsed.data.swappedAt}:00+05:30`).toISOString()});revalidatePath("/rentals");revalidatePath("/bookings");revalidatePath("/fleet");revalidatePath("/");return{status:"success",message:`${result.rentalNumber} vehicle swapped`};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Unable to swap vehicle"};}}

const damageItemSchema=z.object({description:z.string().trim().min(3).max(500),amount:z.coerce.number().finite().min(0).multipleOf(0.01),evidenceMetadata:z.array(z.unknown()).default([])});
const returnSchema=z.object({rentalId:z.string().uuid(),returnedAt:z.iso.datetime({local:true}),returnOdometer:z.coerce.number().int().min(0).max(10000000),batteryLevel:z.coerce.number().int().min(0).max(100),condition:z.enum(["excellent","good","fair","damaged"]),notes:z.string().trim().max(2000).optional(),vehicleDisposition:z.enum(["available","maintenance"]),damageItems:z.string().default("[]").transform((value,ctx)=>{try{const parsed=JSON.parse(value);const result=z.array(damageItemSchema).safeParse(parsed);if(!result.success){ctx.addIssue({code:"custom",message:result.error.issues[0]?.message??"Check damage items"});return z.NEVER;}return result.data;}catch{ctx.addIssue({code:"custom",message:"Damage items must be valid JSON"});return z.NEVER;}}),evidenceMetadata:z.string().default("[]").transform((value,ctx)=>{try{const parsed=JSON.parse(value);const result=z.array(z.unknown()).safeParse(parsed);if(!result.success){ctx.addIssue({code:"custom",message:"Evidence metadata must be an array"});return z.NEVER;}return result.data;}catch{ctx.addIssue({code:"custom",message:"Evidence metadata must be valid JSON"});return z.NEVER;}})});
export async function recordRentalReturnAction(_:RentalActionState,formData:FormData):Promise<RentalActionState>{const raw=Object.fromEntries(formData);const parsed=returnSchema.safeParse(raw);if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check return inspection details"};try{const result=await recordRentalReturn({...parsed.data,returnedAt:new Date(`${parsed.data.returnedAt}:00+05:30`).toISOString(),checklist:{battery:formData.get("checklistBattery")==="on",charger:formData.get("checklistCharger")==="on",helmet:formData.get("checklistHelmet")==="on",documents:formData.get("checklistDocuments")==="on"}});revalidatePath("/rentals");revalidatePath("/fleet");revalidatePath("/");return{status:"success",message:`${result.rentalNumber} returned · vehicle ${result.vehicleStatus}${result.damageTotal>0?` · ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(result.damageTotal)} damage charges recorded`:""}`};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Unable to record return inspection"};}}

const settlementSchema=z.object({rentalId:z.string().uuid()});
export async function settleRental(_:RentalActionState,formData:FormData):Promise<RentalActionState>{const parsed=settlementSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{status:"error",message:parsed.error.issues[0]?.message??"Check settlement details"};try{const result=await settleReturnedRental(parsed.data);revalidatePath("/rentals");revalidatePath("/payments");revalidatePath("/fleet");revalidatePath("/");const due=result.amountDue>0?` · ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(result.amountDue)} due`:result.depositRefundDue>0?` · ${new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(result.depositRefundDue)} deposit refund due`:" · fully reconciled";return{status:"success",message:`${result.rentalNumber} settled${due}`};}catch(error){return{status:"error",message:error instanceof Error?error.message:"Unable to settle rental"};}}
