"use client";

import { useActionState, useId, useState } from "react";
import { useFormStatus } from "react-dom";
import { CalendarDays, CircleCheckBig, Plus, ReceiptIndianRupee, Tag } from "lucide-react";
import { addPricingPlan, editPricingPlan, initialPricingActionState, initialQuoteActionState, previewPricingQuote } from "@/app/(dashboard)/pricing/actions";
import type { PricingPlan, PricingWorkspaceData } from "@/lib/services/pricing";
import { StatusBadge } from "@/components/feedback/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });

export function PricingWorkspace({ data }: { data: PricingWorkspaceData }) {
  const [showInactive, setShowInactive] = useState(false);
  const plans = data.plans.filter((plan) => showInactive || plan.status === "active");
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Tag} label="All plans" value={data.totals.all} /><Metric icon={CircleCheckBig} label="Active" value={data.totals.active} /><Metric icon={CalendarDays} label="Daily" value={data.totals.daily} /><Metric icon={CalendarDays} label="Weekly" value={data.totals.weekly} /><Metric icon={CalendarDays} label="Monthly" value={data.totals.monthly} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(320px,0.8fr)]"><Card className="border-border/80 bg-card/90"><CardHeader className="gap-4 border-b border-border/70 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>Rate cards</CardTitle><CardDescription>Company pricing used for rental quotes and future immutable contract snapshots.</CardDescription></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setShowInactive((value) => !value)}>{showInactive ? "Hide inactive" : "Show inactive"}</Button>{data.canManage && <PlanDialog />}</div></CardHeader><CardContent className="p-0"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-border/70 bg-muted/20 text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Rate</th><th className="px-4 py-3">Allowance</th><th className="px-4 py-3">Duration</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-border/60">{plans.map((plan)=><PlanRow key={plan.id} plan={plan} canManage={data.canManage} />)}</tbody></table></div><div className="divide-y divide-border/60 md:hidden">{plans.map((plan)=><PlanMobile key={plan.id} plan={plan} canManage={data.canManage} />)}</div>{plans.length===0&&<p className="p-10 text-center text-sm text-muted-foreground">No pricing plans in this view.</p>}</CardContent></Card><QuoteCard plans={data.plans.filter((plan)=>plan.status==="active")} taxPercentage={data.taxPercentage} /></div>
  </div>;
}

function PlanRow({plan,canManage}:{plan:PricingPlan;canManage:boolean}) { return <tr><td className="px-4 py-3"><p className="font-semibold">{plan.name}</p><p className="text-xs text-muted-foreground">{plan.code}{plan.vehicleCategory?` · ${plan.vehicleCategory}`:" · All vehicles"}</p></td><td className="px-4 py-3"><p className="font-semibold">{money.format(plan.baseRate)} / {plan.billingUnit}</p><p className="text-xs text-muted-foreground">Deposit {money.format(plan.depositAmount)}</p></td><td className="px-4 py-3">{plan.includedKm} km <span className="text-muted-foreground">+ {money.format(plan.extraKmRate)}/km</span></td><td className="px-4 py-3">{plan.minimumDays}–{plan.maximumDays??"∞"} days</td><td className="px-4 py-3"><StatusBadge status={plan.status}/></td><td className="px-4 py-3 text-right">{canManage?<PlanDialog plan={plan}/>:<span className="text-xs text-muted-foreground">View only</span>}</td></tr>; }
function PlanMobile({plan,canManage}:{plan:PricingPlan;canManage:boolean}) { return <div className="space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{plan.name}</p><p className="text-xs text-muted-foreground">{plan.code}</p></div><StatusBadge status={plan.status}/></div><p className="text-lg font-bold">{money.format(plan.baseRate)} <span className="text-xs font-normal text-muted-foreground">/ {plan.billingUnit}</span></p><div className="flex flex-wrap gap-2"><Badge variant="outline">{plan.includedKm} km included</Badge><Badge variant="secondary">{plan.minimumDays}–{plan.maximumDays??"∞"} days</Badge></div>{canManage&&<PlanDialog plan={plan}/>}</div>; }

function PlanDialog({plan}:{plan?:PricingPlan}) { const [state,action]=useActionState(plan?editPricingPlan.bind(null,plan.id):addPricingPlan,initialPricingActionState); return <Dialog><DialogTrigger asChild><Button size="sm" variant={plan?"outline":"default"}>{plan?"Edit":<><Plus className="mr-2 h-4 w-4"/>Add plan</>}</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{plan?`Edit ${plan.name}`:"Create pricing plan"}</DialogTitle><DialogDescription>Rates are stored in INR. Confirmed rentals will preserve an immutable snapshot in the lifecycle module.</DialogDescription></DialogHeader><PlanForm plan={plan} state={state} action={action}/></DialogContent></Dialog>; }
function PlanForm({plan,state,action}:{plan?:PricingPlan;state:{status:string;message:string};action:(data:FormData)=>void}) { return <form action={action} className="grid gap-4 md:grid-cols-2"><Field label="Plan code" name="code" defaultValue={plan?.code??""} placeholder="WEEKLY_STD" required/><Field label="Plan name" name="name" defaultValue={plan?.name??""} placeholder="Standard Weekly" required/><Field label="Vehicle category" name="vehicleCategory" defaultValue={plan?.vehicleCategory??""} placeholder="All vehicles"/><SelectField label="Billing unit" name="billingUnit" defaultValue={plan?.billingUnit??"week"} options={[["day","Day"],["week","Week"],["month","Month"]]}/><Field label="Base rate (₹)" name="baseRate" defaultValue={String(plan?.baseRate??0)} type="number" min={0} step="0.01" required/><Field label="Deposit (₹)" name="depositAmount" defaultValue={String(plan?.depositAmount??0)} type="number" min={0} step="0.01" required/><Field label="Included km / unit" name="includedKm" defaultValue={String(plan?.includedKm??0)} type="number" min={0} step="0.01" required/><Field label="Extra km rate (₹)" name="extraKmRate" defaultValue={String(plan?.extraKmRate??0)} type="number" min={0} step="0.01" required/><Field label="Minimum days" name="minimumDays" defaultValue={String(plan?.minimumDays??1)} type="number" min={1} required/><Field label="Maximum days" name="maximumDays" defaultValue={String(plan?.maximumDays??"")} type="number" min={1}/><Field label="Effective from" name="effectiveFrom" defaultValue={plan?.effectiveFrom??new Date().toISOString().slice(0,10)} type="date" required/><Field label="Effective to" name="effectiveTo" defaultValue={plan?.effectiveTo??""} type="date"/><SelectField label="Status" name="status" defaultValue={plan?.status??"active"} options={[["active","Active"],["inactive","Inactive"]]}/><label className="flex items-center gap-3 self-end rounded-lg border border-border p-3 text-sm"><input type="checkbox" name="taxInclusive" defaultChecked={plan?.taxInclusive??false}/>Tax included in rate</label><div className="space-y-2 md:col-span-2"><Label>Description</Label><Textarea name="description" defaultValue={plan?.description??""} maxLength={500} rows={3}/></div><p role="status" className={`text-sm md:col-span-2 ${state.status==="error"?"text-destructive":"text-emerald-500"}`}>{state.message}</p><div className="flex justify-end md:col-span-2"><SubmitButton label={plan?"Save plan":"Create plan"}/></div></form>; }

function QuoteCard({plans,taxPercentage}:{plans:PricingPlan[];taxPercentage:number}) { const [state,action]=useActionState(previewPricingQuote,initialQuoteActionState); const q=state.quote; return <Card className="h-fit border-border/80 bg-card/90"><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptIndianRupee className="h-5 w-5 text-primary"/>Quote preview</CardTitle><CardDescription>Calculated securely from live rates. Tax setting: {taxPercentage}%.</CardDescription></CardHeader><CardContent className="space-y-4"><form action={action} className="space-y-4"><SelectField label="Active plan" name="planId" defaultValue={plans[0]?.id??""} options={plans.map((plan)=>[plan.id,plan.name])}/><Field label="Duration (days)" name="durationDays" defaultValue="7" type="number" min={1} required/><Field label="Estimated distance (km)" name="estimatedKm" defaultValue="100" type="number" min={0} step="0.01" required/><SubmitButton label="Calculate quote" disabled={plans.length===0}/></form><p role="status" className={state.status==="error"?"text-sm text-destructive":"text-sm text-emerald-500"}>{state.message}</p>{q&&<div className="space-y-2 rounded-xl border border-border bg-muted/20 p-4 text-sm"><Line label={`${q.billingUnits} billing unit(s)`} value={money.format(q.rentalAmount)}/><Line label={`Excess ${q.excessKm} km`} value={money.format(q.excessKmCharge)}/><Line label={`Tax (${q.taxPercentage}%)`} value={money.format(q.taxAmount)}/><Line label="Refundable deposit" value={money.format(q.depositAmount)}/><div className="mt-3 flex justify-between border-t border-border pt-3 text-base font-bold"><span>Total payable</span><span>{money.format(q.totalPayable)}</span></div></div>}</CardContent></Card>; }
function Line({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span>{value}</span></div>; }
function SubmitButton({label,disabled=false}:{label:string;disabled?:boolean}) { const {pending}=useFormStatus(); return <Button type="submit" disabled={pending||disabled}>{pending?"Working…":label}</Button>; }
function Field({label,name,defaultValue,...props}:{label:string;name:string;defaultValue:string}&Omit<React.ComponentProps<typeof Input>,"name"|"defaultValue">) { const id=useId(); return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} name={name} defaultValue={defaultValue} {...props}/></div>; }
function SelectField({label,name,defaultValue,options}:{label:string;name:string;defaultValue:string;options:string[][]}) { const id=useId(); return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><select id={id} name={name} defaultValue={defaultValue} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" required>{options.length===0&&<option value="">No active plans</option>}{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></div>; }
function Metric({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:number}) { return <Card className="border-border/80 bg-card/90"><CardContent className="flex items-center gap-3 p-4"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><Icon className="h-5 w-5"/></div><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></CardContent></Card>; }
