import "server-only";
import { createClient } from "@/lib/supabase/server";

type Permissions=Record<string,string[]>;
export interface AvailableVehicle { id:string; serialNumber:string; model:string; category:string; batteryLevel:number }
export interface BookingOption { id:string; label:string }
export interface BookingRecord { id:string; number:string; customer:string; vehicle:string; startsAt:string; endsAt:string; status:string; total:number }
export interface BookingWorkspaceData { bookings:BookingRecord[]; customers:BookingOption[]; plans:BookingOption[]; canCreate:boolean; totals:{all:number;pending:number;confirmed:number;upcoming:number} }

function permissionsFrom(value:unknown):Permissions { if(!value||typeof value!=="object"||Array.isArray(value))return{}; return Object.fromEntries(Object.entries(value).filter(([,v])=>Array.isArray(v))) as Permissions; }
function allowed(role:string,p:Permissions,actions:string[]){if(role==="admin"||role==="super_admin")return true;const a=Object.entries(p).find(([k])=>k.toLowerCase()==="rentals")?.[1]??[];return a.some(x=>actions.some(y=>x.toLowerCase()===y.toLowerCase()));}
async function actor(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Authentication required");const {data:profile}=await supabase.from("profiles").select("id,company_id,role,status").eq("id",user.id).is("deleted_at",null).maybeSingle();if(!profile||profile.status!=="active")throw new Error("Active employee profile required");const {data:r}=await supabase.from("roles").select("permissions").eq("company_id",profile.company_id).eq("name",profile.role).is("deleted_at",null).maybeSingle();return{supabase,user,profile,permissions:permissionsFrom(r?.permissions)};}
const money=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const round=(v:number)=>Math.round((v+Number.EPSILON)*100)/100;

export async function getBookingWorkspace():Promise<BookingWorkspaceData>{const a=await actor();if(!allowed(a.profile.role,a.permissions,["View","Create","Edit","Manage"]))throw new Error("You do not have permission to view bookings");const [b,c,p]=await Promise.all([
 a.supabase.from("bookings").select("id,booking_number,starts_at,ends_at,status,total_amount,customers(full_name),bikes(serial_number,model)").eq("company_id",a.profile.company_id).is("deleted_at",null).order("created_at",{ascending:false}),
 a.supabase.from("customers").select("id,full_name,customer_number").eq("company_id",a.profile.company_id).eq("status","active").eq("kyc_status","verified").is("deleted_at",null).order("full_name"),
 a.supabase.from("pricing_plans").select("id,name,code").eq("company_id",a.profile.company_id).eq("status","active").is("deleted_at",null).order("name")]);
 const err=b.error??c.error??p.error;if(err)throw new Error(`Unable to load bookings: ${err.message}`);const rows=(b.data??[]) as unknown as Array<Record<string,unknown>>;const bookings=rows.map(r=>{const customer=r.customers as Record<string,unknown>|null;const bike=r.bikes as Record<string,unknown>|null;return{id:String(r.id),number:String(r.booking_number),customer:String(customer?.full_name??"Unknown"),vehicle:`${String(bike?.serial_number??"")} · ${String(bike?.model??"")}`,startsAt:String(r.starts_at),endsAt:String(r.ends_at),status:String(r.status),total:money(r.total_amount)}});const now=new Date().toISOString();return{bookings,customers:(c.data??[]).map(x=>({id:x.id,label:`${x.full_name} · ${x.customer_number}`})),plans:(p.data??[]).map(x=>({id:x.id,label:`${x.name} · ${x.code}`})),canCreate:allowed(a.profile.role,a.permissions,["Create","Edit","Manage"]),totals:{all:bookings.length,pending:bookings.filter(x=>x.status==="pending").length,confirmed:bookings.filter(x=>x.status==="confirmed").length,upcoming:bookings.filter(x=>x.status==="confirmed"&&x.startsAt>now).length}};}

export async function findAvailableVehicles(startsAt:string,endsAt:string):Promise<AvailableVehicle[]>{const a=await actor();if(!allowed(a.profile.role,a.permissions,["View","Create","Edit","Manage"]))throw new Error("You do not have permission to search availability");const [b,r,c]=await Promise.all([
 a.supabase.from("bikes").select("id,serial_number,model,category,battery_level").eq("company_id",a.profile.company_id).eq("status","available").is("deleted_at",null).order("serial_number"),
 a.supabase.from("rentals").select("bike_id").eq("company_id",a.profile.company_id).in("status",["active","overdue"]).is("deleted_at",null),
 a.supabase.from("bookings").select("bike_id").eq("company_id",a.profile.company_id).in("status",["pending","confirmed"]).is("deleted_at",null).lt("starts_at",endsAt).gt("ends_at",startsAt)]);
 const err=b.error??r.error??c.error;if(err)throw new Error(err.message);const blocked=new Set([...(r.data??[]).map(x=>x.bike_id),...(c.data??[]).map(x=>x.bike_id)]);return(b.data??[]).filter(x=>!blocked.has(x.id)).map(x=>({id:x.id,serialNumber:x.serial_number,model:x.model,category:x.category??"",batteryLevel:x.battery_level??100}));}

export interface CreateBookingInput{customerId:string;bikeId:string;planId:string;startsAt:string;endsAt:string;estimatedKm:number;status:"pending"|"confirmed";notes:string}
export async function createBooking(input:CreateBookingInput){const a=await actor();if(!allowed(a.profile.role,a.permissions,["Create","Edit","Manage"]))throw new Error("You do not have permission to create bookings");const available=await findAvailableVehicles(input.startsAt,input.endsAt);if(!available.some(v=>v.id===input.bikeId))throw new Error("Vehicle is no longer available for this period");const [customer,plan,settings]=await Promise.all([
 a.supabase.from("customers").select("id").eq("id",input.customerId).eq("company_id",a.profile.company_id).eq("status","active").eq("kyc_status","verified").is("deleted_at",null).single(),
 a.supabase.from("pricing_plans").select("id,code,name,billing_unit,base_rate,included_km,extra_km_rate,deposit_amount,minimum_days,maximum_days,tax_inclusive,effective_from,effective_to").eq("id",input.planId).eq("company_id",a.profile.company_id).eq("status","active").is("deleted_at",null).single(),
 a.supabase.from("rental_settings").select("tax_percentage").eq("company_id",a.profile.company_id).single()]);const err=customer.error??plan.error??settings.error;if(err||!plan.data)throw new Error(err?.message??"Booking inputs unavailable");const days=Math.ceil((new Date(input.endsAt).getTime()-new Date(input.startsAt).getTime())/86400000);if(days<plan.data.minimum_days||(plan.data.maximum_days&&days>plan.data.maximum_days))throw new Error("Duration is outside the selected plan limits");const unit=plan.data.billing_unit==="day"?1:plan.data.billing_unit==="week"?7:30,units=Math.ceil(days/unit),rental=round(units*money(plan.data.base_rate)),included=units*money(plan.data.included_km),excess=Math.max(0,input.estimatedKm-included),excessCharge=round(excess*money(plan.data.extra_km_rate)),taxRate=money(settings.data?.tax_percentage),taxable=rental+excessCharge,tax=plan.data.tax_inclusive?round(taxable*taxRate/(100+taxRate)):round(taxable*taxRate/100),total=round(taxable+(plan.data.tax_inclusive?0:tax)+money(plan.data.deposit_amount));const snapshot={version:1,planId:plan.data.id,code:plan.data.code,name:plan.data.name,billingUnit:plan.data.billing_unit,billingUnits:units,durationDays:days,baseRate:money(plan.data.base_rate),rentalAmount:rental,includedKm:included,estimatedKm:input.estimatedKm,excessKm:excess,extraKmRate:money(plan.data.extra_km_rate),excessKmCharge:excessCharge,taxInclusive:plan.data.tax_inclusive,taxPercentage:taxRate,taxAmount:tax,depositAmount:money(plan.data.deposit_amount),totalPayable:total,calculatedAt:new Date().toISOString()};const stamp=new Date().toISOString().slice(0,10).replaceAll("-","");const suffix=crypto.randomUUID().replaceAll("-","").slice(0,6).toUpperCase();const {error}=await a.supabase.from("bookings").insert({company_id:a.profile.company_id,booking_number:`BKG-${stamp}-${suffix}`,customer_id:input.customerId,bike_id:input.bikeId,pricing_plan_id:input.planId,starts_at:input.startsAt,ends_at:input.endsAt,estimated_km:input.estimatedKm,status:input.status,pricing_snapshot:snapshot,total_amount:total,notes:input.notes||null,confirmed_at:input.status==="confirmed"?new Date().toISOString():null,created_by:a.user.id,updated_by:a.user.id});if(error)throw new Error(error.code==="23P01"?"Vehicle was just booked for an overlapping period":error.message);return{number:`BKG-${stamp}-${suffix}`,total};}
