import "server-only";

import { createClient } from "@/lib/supabase/server";

type Permissions = Record<string, string[]>;
export interface ActivatableBooking { id:string; number:string; customer:string; vehicle:string; startsAt:string; endsAt:string; currentOdometer:number; total:number }
export interface RentalRecord { id:string; number:string; customer:string; vehicle:string; startedAt:string; plannedEndAt:string; startOdometer:number; status:string; contractAmount:number; extensionAmount:number; total:number }
export interface RentalWorkspaceData { rentals:RentalRecord[]; confirmedBookings:ActivatableBooking[]; canActivate:boolean; canExtend:boolean; totals:{active:number;dueToday:number;overdue:number;confirmed:number} }

function permissionsFrom(value:unknown):Permissions { if(!value||typeof value!=="object"||Array.isArray(value))return{};return Object.fromEntries(Object.entries(value).filter(([,v])=>Array.isArray(v))) as Permissions; }
function allowed(role:string,p:Permissions,actions:string[]){if(role==="admin"||role==="super_admin")return true;const a=Object.entries(p).find(([k])=>k.toLowerCase()==="rentals")?.[1]??[];return a.some(x=>actions.some(y=>x.toLowerCase()===y.toLowerCase()));}
async function actor(){const supabase=await createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw new Error("Authentication required");const{data:profile,error:profileError}=await supabase.from("profiles").select("id,company_id,role,status").eq("id",user.id).is("deleted_at",null).maybeSingle();if(profileError||!profile||profile.status!=="active")throw new Error("Active employee profile required");const{data:r,error:roleError}=await supabase.from("roles").select("permissions").eq("company_id",profile.company_id).eq("name",profile.role).is("deleted_at",null).maybeSingle();if(roleError)throw new Error(roleError.message);return{supabase,profile,permissions:permissionsFrom(r?.permissions)};}
const money=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};

export async function getRentalWorkspace():Promise<RentalWorkspaceData>{const a=await actor();if(!allowed(a.profile.role,a.permissions,["View","Create","Edit","Manage"]))throw new Error("You do not have permission to view rentals");const[r,b]=await Promise.all([
 a.supabase.from("rentals").select("id,rental_number,started_at,planned_end_at,start_odometer,status,contract_amount,extension_amount,total_amount,customers(full_name),bikes(serial_number,model)").eq("company_id",a.profile.company_id).is("deleted_at",null).order("created_at",{ascending:false}),
 a.supabase.from("bookings").select("id,booking_number,starts_at,ends_at,total_amount,customers(full_name),bikes(serial_number,model,current_odometer)").eq("company_id",a.profile.company_id).eq("status","confirmed").is("deleted_at",null).order("starts_at")]);
 const error=r.error??b.error;if(error)throw new Error(`Unable to load rentals: ${error.message}`);const rentals=((r.data??[]) as unknown as Record<string,unknown>[]).map(x=>{const c=x.customers as Record<string,unknown>|null,v=x.bikes as Record<string,unknown>|null;return{id:String(x.id),number:String(x.rental_number??"Legacy rental"),customer:String(c?.full_name??"Unknown"),vehicle:`${String(v?.serial_number??"")} · ${String(v?.model??"")}`,startedAt:String(x.started_at),plannedEndAt:String(x.planned_end_at??""),startOdometer:money(x.start_odometer),status:String(x.status),contractAmount:money(x.contract_amount),extensionAmount:money(x.extension_amount),total:money(x.total_amount)}});const confirmedBookings=((b.data??[]) as unknown as Record<string,unknown>[]).map(x=>{const c=x.customers as Record<string,unknown>|null,v=x.bikes as Record<string,unknown>|null;return{id:String(x.id),number:String(x.booking_number),customer:String(c?.full_name??"Unknown"),vehicle:`${String(v?.serial_number??"")} · ${String(v?.model??"")}`,startsAt:String(x.starts_at),endsAt:String(x.ends_at),currentOdometer:money(v?.current_odometer),total:money(x.total_amount)}});const now=new Date(),end=new Date(now);end.setHours(23,59,59,999);return{rentals,confirmedBookings,canActivate:allowed(a.profile.role,a.permissions,["Create","Edit","Manage"]),canExtend:allowed(a.profile.role,a.permissions,["Edit","Manage"]),totals:{active:rentals.filter(x=>x.status==="active").length,dueToday:rentals.filter(x=>x.status==="active"&&x.plannedEndAt&&new Date(x.plannedEndAt)<=end&&new Date(x.plannedEndAt)>=now).length,overdue:rentals.filter(x=>x.status==="overdue"||(x.status==="active"&&x.plannedEndAt&&new Date(x.plannedEndAt)<now)).length,confirmed:confirmedBookings.length}};}

export async function activateBooking(input:{bookingId:string;startedAt:string;startOdometer:number}){const a=await actor();if(!allowed(a.profile.role,a.permissions,["Create","Edit","Manage"]))throw new Error("You do not have permission to activate rentals");const{data,error}=await a.supabase.rpc("activate_confirmed_booking",{p_booking_id:input.bookingId,p_started_at:input.startedAt,p_start_odometer:input.startOdometer});if(error)throw new Error(error.message);const result=Array.isArray(data)?data[0]:data;if(!result)throw new Error("Rental activation did not return a contract");return{rentalId:String(result.rental_id),rentalNumber:String(result.rental_number)};}

export async function extendRental(input:{rentalId:string;extendedEndAt:string;reason?:string}){const a=await actor();if(!allowed(a.profile.role,a.permissions,["Edit","Manage"]))throw new Error("You do not have permission to extend rentals");const{data,error}=await a.supabase.rpc("extend_active_rental",{p_rental_id:input.rentalId,p_extended_end_at:input.extendedEndAt,p_reason:input.reason||null});if(error)throw new Error(error.message);const result=Array.isArray(data)?data[0]:data;if(!result)throw new Error("Rental extension did not return a result");return{rentalNumber:String(result.rental_number),extensionAmount:money(result.extension_amount),newTotal:money(result.new_total)};}
